import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  try {
    const { prompt } = await req.json();

    if (!prompt) {
      return NextResponse.json(
        { error: "Prompt is required" },
        { status: 400 }
      );
    }

    // If OpenAI is configured, use it for code generation
    if (process.env.OPENAI_API_KEY) {
      const response = await fetch(
        "https://api.openai.com/v1/chat/completions",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
          },
          body: JSON.stringify({
            model: "gpt-5.2",
            messages: [
              {
                role: "system",
                content:
                  "You are a code generator. Generate a complete, self-contained HTML file with embedded CSS and JS. Use a pink (#FF69B4, #FF1493) and blue (#00BFFF) color scheme. Return ONLY the HTML code, no explanations.",
              },
              { role: "user", content: prompt },
            ],
            max_tokens: 4000,
          }),
        }
      );

      if (response.ok) {
        const data = await response.json();
        const code = data.choices?.[0]?.message?.content || "";
        return NextResponse.json({ code: code.trim() });
      }
    }

    // Fallback mock response
    const code = `<!DOCTYPE html>
<html>
<head>
  <style>
    body { display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; background: #FAFAFA; font-family: sans-serif; }
    .container { text-align: center; padding: 40px; background: white; border-radius: 16px; box-shadow: 0 4px 24px rgba(0,0,0,0.08); }
    h1 { background: linear-gradient(135deg, #FF69B4, #00BFFF); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
    p { color: #6B6B8A; }
  </style>
</head>
<body>
  <div class="container">
    <h1>Generated by CHLOE</h1>
    <p>Prompt: ${prompt}</p>
    <p>Connect OpenAI API key for AI-powered generation!</p>
  </div>
</body>
</html>`;

    return NextResponse.json({ code });
  } catch (error) {
    console.error("Code generation error:", error);
    return NextResponse.json(
      { error: "Failed to generate code" },
      { status: 500 }
    );
  }
}
